# Generated by Django 4.2.4 on 2023-10-26 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_personal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('image_pic', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('image1', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('image2', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('image3', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('height', models.FloatField()),
                ('diet', models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian'), ('eggterian', 'eggterian')], default='veg', max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('weigth', models.IntegerField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=4)),
                ('physical_disability', models.CharField(choices=[('none', 'no'), ('yes', 'yes')], default='none', max_length=10)),
                ('skin_colour', models.CharField(choices=[('fair', 'Fair'), ('wheatish', 'Wheatish'), ('tanned', 'Tanned'), ('dark', 'Dark'), ('black', 'Black'), ('other', 'Other')], default='fair', max_length=10)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], default='Single', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(default='', max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile_family_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_occupation', models.CharField(max_length=30)),
                ('mothers_occupation', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=20)),
                ('caste', models.CharField(max_length=20)),
                ('mothertounge', models.CharField(max_length=20)),
                ('profile_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile_personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='profile_educational_and_career_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=50)),
                ('collage_name', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('income', models.IntegerField()),
                ('profile_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile_personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='partner_preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agemin', models.IntegerField()),
                ('agemax', models.IntegerField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], default='Single', max_length=10)),
                ('height', models.IntegerField()),
                ('religion', models.CharField(max_length=20)),
                ('caste', models.CharField(max_length=20)),
                ('mothertounge', models.CharField(max_length=20)),
                ('qualificaton', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('income', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('profile_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile_personal_info')),
            ],
        ),
    ]
