# Generated by Django 4.2.4 on 2023-10-28 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('image_pic', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=20)),
                ('caste', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
