# Generated by Django 4.2.4 on 2023-10-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='image_pic',
        ),
    ]
